services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next  # Volumen separado para .next
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0

  app-prod:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    profiles:
      - production

volumes:
  node_modules:
  next_cache: