services:
  next-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
    user: "1000:1000"

  next-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    profiles:
      - production
    restart: unless-stopped
volumes:
  node_modules: